linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - fieldalignment

  staticcheck:
    checks: ["all"]

  revive:
    ignore-generated-header: false

  gosec:
    exclude: ["G104"]

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec
    - unused
    - gosimple
    - stylecheck
    - gocritic
    - asciicheck
    - goconst
    - gocyclo
  disable:
    - typecheck 

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true

modules-download-mode: readonly

